### ISSUE TITLE
Terminology discrepancy between silhouette-regmarks and inkscape-silhouette

### ISSUE THREAD

**Issue by ktosiek** [miLORD1337/silhouette-regmarks#1]
Hello! I've started using this plugin lately, and I've noticed "X/Y mark distance" is interpreted differently here and in inkscape-silhouette:
in silhouette-regmarks "X mark distance" means the absolute X where the mark lines meet, but in inkscape-silhouette it's the distance from the black rectangle to the place where mark lines meet.

For example, if I use "X mark distance": 200, "Y mark distance": 292, Position from top/left: 10 with this plugin, then I need to use "X mark distance": 190, "Y mark distance": 282, Position from top/left: 10 in inkscape-silhouette.

Would it make sense to change this plugin to use the same terminology as the inkscape-silhouette one?

**Comment by miLORD1337** [comment]
Hey, 
sorry for not answering, I somehow didn't get notified. I could change that, but lately this functionality got integrated into inkscape-silhouette. Maybe you have seen it already? Please give it a try and see how it works out for you. If there's some discrepancy left, you could open an issue over there.
Kind regards,
miLORD
